---
- name: Create app
  dokku_app:
    app: "{{ app_name }}"

- name: Set domains
  dokku_domains:
    app: "{{ app_name }}"
    domains: "{{ app_secrets.app_domains | default([]) }}"
    state: set

- name: Create postgres service
  environment: "{{ app_configs.postgres.environment | default({}) }}"
  dokku_service_create:
    name: "{{ app_secrets.postgres.name }}"
    service: postgres
  when: app_secrets.postgres is defined

- name: Link postgres service
  dokku_service_link:
    app: "{{ app_name }}"
    name: "{{ app_secrets.postgres.name }}"
    service: postgres
  when: app_secrets.postgres is defined

- name: Add environment variables
  dokku_config:
    app: "{{ app_name }}"
    config: "{{ app_secrets.config | default({}) }}"
