---
- name: Create app
  dokku_app:
    app: "{{ app_name }}"

- name: Create postgres service
  environment: "{{ postgres.environment | default({}) }}"
  dokku_service_create:
    name: "{{ postgres.name }}"
    service: postgres
  when: postgres is defined

- name: Link postgres service
  dokku_service_link:
    app: "{{ app_name }}"
    name: "{{ postgres.name }}"
    service: postgres
  when: postgres is defined

- name: Enable letsencrypt
  shell:
    cmd: "dokku letsencrypt:enable {{ app_name }}"
  when: letsencrypt is true

- name: Add environemnt variables
  dokku_config:
    app: "{{ app_name }}"
    config: "{{ config | default({}) }}"

- name: Add domains
  dokku_domains:
    app: "{{ app_name }}"
    domains: "{{ app_domains | default([]) }}"
