---
- name: Create app
  dokku_app:
    app: "{{ app_name }}"

- name: Add domains
  dokku_domains:
    app: "{{ app_name }}"
    domains: "{{ app_secrets.app_domains | default([]) }}"

- name: Create postgres service
  environment: "{{ app_configs.postgres.environment | default({}) }}"
  dokku_service_create:
    name: "{{ app_secrets.postgres.name }}"
    service: postgres
  when: app_secrets.postgres is defined

- name: Link postgres service
  dokku_service_link:
    app: "{{ app_name }}"
    name: "{{ app_secrets.postgres.name }}"
    service: postgres
  when: app_secrets.postgres is defined

- name: Enable letsencrypt
  dokku_letsencrypt:
    app: "{{ app_name }}"
  when: app_secrets.letsencrypt | bool

- name: Add environemnt variables
  dokku_config:
    app: "{{ app_name }}"
    config: "{{ app_secrets.config | default({}) }}"
