---
- name: Test that app deployed successfully
  ansible.builtin.uri:
    url: "http://{{ app_secrets.app_domains[0]}}"
    return_content: true
    follow_redirects: all
  register: res
  ignore_errors: true

- name: Enable letsencrypt
  dokku_letsencrypt:
    app: "{{ app_name }}"
  when: res is not failed
