---
- name: Check if domain zone exists
  community.dns.hetzner_dns_zone_info:
    zone_name: "{{ domain }}"
  register: zone_info_result
  ignore_errors: yes

- name: Create DNS Zone for domain
  when: zone_info_result.failed is true and zone_info_result.msg == "Zone not found"
  uri:
    method: POST
    url: "https://dns.hetzner.com/api/v1/zones"
    body_format: "json"
    body:
      "name": "{{ domain }}"
      "ttl": 3600
    headers:
      "Content-Type": application/json'
      "Auth-API-Token": "{{ hetzner_token }}"

- name: Set up domain
  community.dns.hetzner_dns_record:
    state: present
    zone_name: "{{ domain }}"
    type: A
    record: "{{ domain }}"
    value: "{{ hcloud_server_address }}"
    ttl: 3600

- name: Set up wildcard domain
  community.dns.hetzner_dns_record:
    state: present
    zone_name: "{{ domain }}"
    type: A
    record: "*.{{ domain }}"
    value: "{{ hcloud_server_address }}"
    ttl: 3600
