roles:
  - name: dokku_bot.ansible_dokku
    version: v2022.10.17
  - name: geerlingguy.docker
    src: geerlingguy.docker
    version: 7.0.1

collections:
  - name: hetzner.hcloud
    version: 2.1.1
  - name: community.dns
    version: 2.6.2
  - name: community.general
    version: 7.4.0
  - name: ansible.posix
    verions: 1.5.4
  - name: community.docker
    verions: 3.4.10