---
roles:
  - name: dokku_bot.ansible_dokku
    version: v2022.10.17

collections:
  - name: hetzner.hcloud
    version: 2.1.1
  - name: community.dns
    version: 2.6.1
  - name: community.general
    version: 7.4.0
  - name: ansible.posix
    verions: 1.5.4
...