---
- name: Import app secrets
  delegate_to: localhost
  include_vars:
    file: "{{ playbook_dir }}/../inventories/{{ env }}/apps/{{ app_name }}.secrets.yml"
  tags: "app={{ app_name }}"

- name: Run initial app configuration
  import_role:
    name: dokku_app
  tags: "app={{ app_name }}"

- name: Run any additional app configurations
  import_tasks: "apps/{{ app_name }}/tasks/extended_config.yml"
  tags: "app={{ app_name }}"
