---
- name: Import app secrets
  delegate_to: localhost
  include_vars:
    file: "{{ playbook_dir }}/../inventories/{{ env }}/apps/{{ app_name }}.secrets.yml"
    name: app_secrets
  tags: "app={{ app_name }}"

- name: Enable letsencrypt for app
  import_role:
    name: letsencrypt_app
  when: app_secrets.letsencrypt | bool
  tags: "app={{ app_name }}"
