---
- name: Make app secrets.yml
  template:
    src: templates/app.secrets.yml.example
    dest: "{{ app_env_secrets_dir }}/{{ app_name }}.secrets.yml"
    force: no

- name: Make app config directory
  file:
    path: "apps/{{ app_name }}/tasks"
    state: directory
    recurse: yes

- name: Make placeholder extended_config.yml
  template:
    src: templates/extended_config.yml
    dest: "apps/{{ app_name }}/tasks/extended_config.yml"
    force: no
