---
- name: Perform full patching
  apt:
    name: '*'
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Setup passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Create new sudo user
  import_tasks: sudo_user.yml

- name: Make changes to sshd_config
  import_tasks: sshd.yml
  notify: Restart SSH

- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Allow Http traffic
  community.general.ufw:
    rule: allow
    port: '80,443'
    proto: tcp

- name: UFW - Deny all other traffic by default
  community.general.ufw:
    state: enabled
    default: deny

- name: Update apt and install required system packages
  apt:
    state: latest
    pkg:
      - curl
      - vim
      - nano
      - ufw
      - fail2ban

- name: Check reboot status
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: reboot
  changed_when: reboot.stat.exists
  notify: Reboot Server