---
- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Disable password authentication for everyone
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'

- name: Set Log level
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?LogLevel'
    line: 'LogLevel VERBOSE'
