---
- name: Build and setup a new server on Hetzner Cloud
  hosts: localhost
  roles:
    - role: hetzner

- name: Create DNS records on Hetzner Cloud
  hosts: localhost
  tasks:
    - import_tasks: roles/hetzner/tasks/dns.yml
      vars:
        domain: supergood.site
        hetzner_token: "{{ lookup('ansible.builtin.env', 'HETZNER_DNS_TOKEN') }}"

- name: Setup a new server on Hetzner Cloud
  hosts: supergood
  roles:
    - role: ubuntu
      vars:
        - created_username: nick

# - name: Install Dokku on new server
#   hosts: supergood
#   tasks:
#     - import_tasks: roles/dokku/tasks/install.yml
#       vars:
