---
- name: Provision a new server on Hetzner Cloud
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    site_domain: supergood.site
    hetzner_server_name: supergood-site
    # The project_label value is used by the label_selector in dynamic inventory files.
    hetzner_project_label: supergood
    hetzner_ssh_key_name: nick-macbook
  vars_files:
    - "../inventories/{{ env }}/host_vars/localhost/hetzner_provision_overrides.yml"
  roles:
    - hetzner_provision
    - cloudflare_dns