---
- name: Configure Dokku Apps
  hosts: supergood_cloud
  gather_facts: true
  vars:
    invoked_by_script: false
    placeholder_app_repo: "https://github.com/Niicck/supergood-placeholder.git"
    placeholder_app_version: main
  tasks:
    - name: Ensure that this playbook was invoked by python script
      assert:
        that:
          - invoked_by_script
        fail_msg: "Don't run this playbook directly. Please run `python configure_apps.py {{env}} ...` instead."

    - name: Run role without running any tasks
      # See: https://github.com/dokku/ansible-dokku/pull/137#issuecomment-1280024359
      import_role: 
        name: dokku_bot.ansible_dokku
        tasks_from: init.yml

    - name: "Configure apps"
      include_tasks: tasks/configure_single_app.yml
      loop_control:
        loop_var: app_name
      loop: "{{ apps }}"
