---
- name: Configure dokku host server
  hosts: supergood_dokku
  gather_facts: false
  vars:
    created_username: nick
  tasks:
    - name: Attempt SSH with created_username
      command: 'ssh -o PasswordAuthentication=no -o ConnectTimeout=5 {{ created_username }}@{{ ipv4 }} exit'
      register: ssh_check
      ignore_errors: true
      delegate_to: localhost

    - name: Set remote_user to "root" if created_username hasn't been created yet
      set_fact:
        remote_user: root
      when: ssh_check is failed

    - name: Run ubuntu configurations
      remote_user: "{{ remote_user | default('nick') }}"
      become: true
      import_role:
        name: ubuntu_initial_setup
