---
- name: Configure supergood ubuntu servers
  hosts: supergood
  gather_facts: false
  tasks:
    - name: Set "created_username" to "ansible_user" from group_vars
      set_fact:
        created_username: "{{ ansible_user }}"

    - name: Attempt SSH with created_username
      command: 'ssh -o ConnectTimeout=5 {{ created_username }}@{{ inventory_hostname }} exit'
      register: ssh_check
      ignore_errors: true
      delegate_to: localhost

    - name: Set ansible_user to "root" user if "created_username" hasn't been created yet.
      set_fact:
        ansible_user: root
      when: ssh_check is failed

    - name: Run ubuntu configurations
      import_role:
        name: configure_ubuntu
