- name: Configure Dokku Apps
  hosts: supergood_dokku
  gather_facts: true
  tasks:
    - name: "Configure apps"
      import_tasks: tasks/configure_single_app.yml
      loop_control:
        loop_var: app_name
      loop: "{{ apps }}"
