---
- name: Configure Dokku Platform
  hosts: supergood_dokku
  vars:
    dokku_packages_state: latest
    docker_users:
      - dokku
      - nick
    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: acl
        url: https://github.com/dokku-community/dokku-acl
    letsencrypt_email: "{{ lookup('env', 'PRIMARY_EMAIL') }}"

  tasks:
    # dokku.dokku_hostname_base if production
    # dokku.env.dokku_hostname_base if non-production
    - name: Set dokku_hostname
      set_fact:
        dokku_hostname: "dokku{{ (env == "production") | ternary('', '.' + env) }}.{{ dokku_hostname_base }}"

    - name: Install dokku
      become: true
      include_role:
        name: dokku_bot.ansible_dokku

    - name: Set global dokku configs
      include_role:
        name: dokku_initial_setup