---
- name: Configure Dokku Platform
  hosts: supergood_dokku
  vars:
    dokku_packages_state: latest

    # dokku_hostname = {{dokku_hostname_base}} if production
    # dokku_hostname = {{env}}.{{dokku_hostname_base}} if non-production
    dokku_hostname: "{{ (env == 'production') | ternary('', env + '.') }}{{ dokku_hostname_base }}"

    dokku_key_file: "/root/.ssh/authorized_keys"

    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: acl
        url: https://github.com/dokku-community/dokku-acl

    letsencrypt_configs:
      email: "{{ lookup('env', 'PRIMARY_EMAIL') }}"
      dns-provider: "hetzner"
      dns-provider-HETZNER_API_KEY: "{{ lookup('env', 'LETSENCRYPT_HETZNER_DNS_TOKEN') }}"
      dns-provider-HETZNER_PROPAGATION_TIMEOUT: 300 # seconds
      dns-provider-HETZNER_POLLING_INTERVAL: 5

  tasks:
    - name: Install dokku
      become: true
      import_role:
        name: dokku_bot.ansible_dokku

    - name: Set global dokku configs
      import_role:
        name: dokku_initial_setup
