---
- name: Configure Dokku Platform
  hosts: supergood_cloud
  vars:
    dokku_packages_state: latest

    # Instead, set ssh-keys with dokku_users
    dokku_skip_key_file: true

    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
      - name: acl
        url: https://github.com/dokku-community/dokku-acl
      - name: redirect
        url: https://github.com/dokku/dokku-redirect.git

    global_letsencrypt_settings:
      email: "{{ lookup('env', 'PRIMARY_EMAIL') }}"
      dns-provider: "cloudflare"
      dns-provider-CLOUDFLARE_DNS_API_TOKEN: "{{ lookup('env', 'LETSENCRYPT_CLOUDFLARE_DNS_API_TOKEN') }}"
      server: default

  tasks:
    - name: Install dokku
      become: true
      import_role:
        name: dokku_bot.ansible_dokku

    - name: Set global letsencrypt configs
      shell:
        cmd: dokku letsencrypt:set --global {{ item.key }} {{ item.value }}
      loop: "{{ global_letsencrypt_settings | dict2items }}"
      no_log: true

    - name: Add letsencrypt autorenewal cron job
      shell:
        cmd: "dokku letsencrypt:cron-job --add"
