---
- name: Provision a new dokku host server
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    domains:
      - supergood.site
      - nickivons.com

    hetzner_ssh_key_name: nick-macbook
    hetzner_server_name_base: supergood-dokku
    
    # The project_label value is used by the label_selector in hcloud.yml dynamic inventory.
    hetzner_project_label: supergood-dokku

  tasks:
    - name: Provision Hetzner server
      import_role:
        name: hetzner_server
