---
- name: Provision a new dokku host server
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    hetzner_ssh_key_name: nick-macbook
    hetzner_server_name_base: supergood-cloud

    # The project_label value is used by the label_selector in hcloud.yml dynamic inventory.
    hetzner_project_label: supergood-cloud

  tasks:
    - name: Provision Hetzner server
      import_role:
        name: hetzner_server

    - name: Create DNS records for domains
      include_role:
        name: cloudflare_dns
      vars:
        domain: "{{ dokku_hostname }}"
