---
- name: Setup local app configs and secrets
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    app_env_secrets_dir: "{{ playbook_dir }}/../inventories/{{ env }}/apps"
  tasks:
    - name: Make app env secrets directory
      file:
        path: "{{ app_env_secrets_dir }}"
        state: directory

    - name: Setup local app configs
      include_tasks: tasks/setup_single_local_app_config.yml
      loop_control:
        loop_var: app_name
      loop: "{{ apps }}"
